"""Remove mentor fields and add routine time ranges

Revision ID: 089b217373cf
Revises: 
Create Date: 2026-01-07 15:15:22.987026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '089b217373cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # First, add new columns to routines table
    with op.batch_alter_table('routines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.Time(), nullable=True))

    # Migrate data: copy scheduled_time to start_time, set end_time = start_time + 1 hour
    conn = op.get_bind()
    conn.execute(sa.text("""
        UPDATE routines
        SET start_time = scheduled_time,
            end_time = time(scheduled_time, '+1 hour')
        WHERE scheduled_time IS NOT NULL
    """))

    # Now drop old columns
    with op.batch_alter_table('routines', schema=None) as batch_op:
        batch_op.drop_column('scheduled_time')
        batch_op.drop_column('difficulty')

    # Remove mentor fields from users table
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('mentor_intensity')
        batch_op.drop_column('mentor_style')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mentor_style', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('mentor_intensity', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('routines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('difficulty', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('scheduled_time', sa.TIME(), nullable=True))
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')

    # ### end Alembic commands ###
